name: flutter_screen_recording_web
description: Web platform implementation of flutter_screen_recording
version: 1.0.2
homepage: "https://github.com/Isvisoft/flutter_screen_recording"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screen_recording_platform_interface: ^1.0.2

  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  platform_detect: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebFlutterScreenRecording
        fileName: flutter_screen_recording_web.dart
