name: flutter_screen_recording
description: A new Flutter plugin for record the screen. This plugin can be used for record the screen on android and iOS devices.
version: 1.1.0
homepage: 'https://github.com/Isvisoft/flutter_screen_recording'

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
#  foreground_service: ^1.3.0
  flutter_foreground_plugin: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.isvisoft.flutter_screen_recording
        pluginClass: FlutterScreenRecordingPlugin
      ios:
        pluginClass: FlutterScreenRecordingPlugin
