name: flutter_screen_recording
description: A new Flutter plugin for record the screen. This plugin can be used for record the screen on android and iOS devices.
version: 1.1.0
homepage: 'https://github.com/Isvisoft/flutter_screen_recording'
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
#  foreground_service: ^1.3.0
  flutter_foreground_plugin:
    git:
      url: https://github.com/jja08111/flutter_foreground_service_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.isvisoft.flutter_screen_recording
        pluginClass: FlutterScreenRecordingPlugin
      ios:
        pluginClass: FlutterScreenRecordingPlugin
